title: Documentation for Ulendo HC
description: An overview of the key features and functionality available from the Ulendo HC plugin
theme: just-the-docs

url: https://heatcompensation-docs.io

aux_links:
  Edit this documentation: https://github.com/s2aulendo/heatcompensation-docs
